import React from "react";
import { Cairo } from "next/font/google";
import Navigation from "@/components/Headers/nav";

const inter = Cairo({ subsets: ["latin"] });

// TYPES
type Props = {
  children: React.ReactNode;
};

// SEO META TAGS
export const metadata = {
  title: "amidco",
  description: "Generated by create next app",
};

export default function layout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
